name: Compila y Genera PDF
on:
  push:

jobs:
  compila:
   runs-on: ubuntu-latest
   name: Cargar, Instalar y Compilar

   steps:
      - name: Hello World GRodriguez
        uses: grodriguez-it/hello-word-jsactions@v1.0
        with:
          who-to-greet: Gustavo
       
      - name: Tener copia local del repo
        uses: actions/checkout@v4
  
      - name: Instalar .NET en el runner
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      
      - name: Instalar dependencias
        run: dotnet restore
      
      - name: Compilar
        run: dotnet build --no-restore

  crear-pdf:
   runs-on: ubuntu-latest
   name: Crear PDF
   
   steps:
      - name: Tener copia local del repo
        uses: actions/checkout@v4
    
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: docs
          output_dir: pdfs
          # Default is true, can set to false to only get PDF files
          build_html: false
          
      - uses: actions/upload-artifact@v4
        with:
          name: docs
          path: pdfs
          
